[pytest]
addopts = --strict-config --strict-markers --durations=20
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
testpaths = tests tests_evo tests_jobs tests_build
xfail_strict = true
